Re introduce fulltext search
BlueBrain/nexus-web pull request #1523
Opened 2024-03-11 07:56 UTC by bilalesi

fixes:  [4723](https://app.zenhub.com/workspaces/blue-brain-nexus-60ace035034cae00105c9307/issues/gh/bluebrain/nexus/4723)
1. add `cmdk` component for fulltext search.
2. use resources list delta endpoint to fetch the results of the query.
3. group the result per org/project in the result component.

## Description

## How has this been tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary unit and integration tests.
- [ ] I have added screenshots (if applicable), in the comment section.

2024-03-11 15:05 UTC, danburonline commented
![CleanShot 2024-03-11 at 4  05 04](https://github.com/BlueBrain/nexus-web/assets/34251194/02142120-be3e-401a-97e1-eb2c22451e0f)

If you have dark mode enabled, the colours look quite off. Have you tested it in dark mode?

2024-03-11 15:09 UTC, danburonline commented
Also, another feedback: Currently, when you're in an input field and type something with a `/`, you always open the command window. Shouldn't we change the shortcut to `CMD + /`? Most apps have it like this.

2024-05-28 10:17 UTC, bilalesi commented
> If you have dark mode enabled, the colours look quite off. Have you tested it in dark mode?

we never take dark mode into consideration, the whole app built with light mode in mind,
This is a discussion for future

2024-05-28 10:18 UTC, bilalesi commented
> Also, another feedback: Currently, when you're in an input field and type something with a `/`, you always open the command window. Shouldn't we change the shortcut to `CMD + /`? Most apps have it like this.

I changed this to `ctrl + e` and will see the endusers feedback

2024-05-28 12:37 UTC, danburonline approved these changes

2024-05-28 12:45 UTC, merged

2024-05-28 12:56 UTC, Dinika requested changes
lgtm. posted a question.

2024-05-28 12:56 UTC, Dinika commented on src/shared/components/FullTextSearch/useFullTextSearch.ts
> +    staleTime: 2,
The `staleTime` in milliseconds right? 2 milliseconds sounds too low to me. Did you mean 2000 ms instead?