Allow Users to login from header
BlueBrain/nexus-web pull request #696
Opened 2020-10-15 05:32 UTC by dhaneshnm

- Add login flow to the login button in the header.

2020-10-15 05:36 UTC, dhaneshnm commented
![Screenshot 2020-10-15 at 07 10 21](https://user-images.githubusercontent.com/1479155/96081202-1f315f00-0eb9-11eb-8fe0-3a433b35cf3e.png)

2020-10-15 05:37 UTC, dhaneshnm commented
![Screenshot 2020-10-15 at 07 35 52](https://user-images.githubusercontent.com/1479155/96081244-34a68900-0eb9-11eb-8c24-1672ed099aa9.png)

2020-10-15 08:06 UTC, Stafeeva submitted a review, later dismissed

2020-10-15 08:07 UTC, kenjinp requested changes

2020-10-15 08:07 UTC, kenjinp commented on src/shared/layouts/FusionMainLayout.tsx
> +    // setPreferredRealm(preferredRealm);
some old comment?

2020-10-15 08:28 UTC, kenjinp approved these changes

2020-10-19 08:36 UTC, Stafeeva approved these changes
Tested in Chrome 💯

2020-10-19 11:01 UTC, kenjinp approved these changes

2020-10-19 11:08 UTC, merged