2807 admin layout tab update
BlueBrain/nexus-web pull request #985
Opened 2021-11-02 13:41 UTC by smitfire

Fixes #

## Description

## How has this been tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary unit and integration tests.
- [ ] I have added screenshots (if applicable), in the comment section.

2021-11-03 12:37 UTC, dhaneshnm approved these changes

2021-11-04 13:40 UTC, nicwells requested changes
There are a few issues picked up by Deep Scan. Also checking against acceptance criteria:

* Deprecate project button not working so was not able to test acceptance criteria related to this
* Settings button still showing in projects listing
* Clicking on studios/workflows opens in new tab/window but then going back to previous view shows tab with no contents. Possible not to switch to the empty tab when clicked?

2021-11-04 13:40 UTC, nicwells commented on src/shared/styles/project-banner.less
> +  // background-color: fade(@header-background-color, 2.5%);
remove rather than comment out

2021-11-04 13:40 UTC, nicwells commented on src/subapps/admin/components/Projects/QueryEditor.tsx
> +            <div style={{ flexGrow: 1 }}>
styles in separate less file? If copy/paste from elsewhere then can leave

2021-11-08 13:09 UTC, dhaneshnm approved these changes

2021-11-08 14:53 UTC, smitfire commented
@nicwells removed settings button, likewise for deprecated. made the change for clicking studio or workflows

2021-11-09 08:11 UTC, merged